title: Big Data Analytics for Sustainability
description: 2<sup>nd</sup> International Workshop on Big Data Analytics for Sustainability (BDA4S)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
